plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.1' //Versione corretta?
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'it.unicam.cs.ids'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // --- Spring Boot Starters ---
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // Opzionale ma consigliato per la validazione dei DTO (sostituirà il tuo custom Validator)
    //implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
    //Validazioni semantiche
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // --- Database H2 ---
    runtimeOnly 'com.h2database:h2' // La versione la decide Spring Boot in automatico

    // --- Spring Security & JWT ---
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // --- Lombok ---
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // --- Testing ---
    testImplementation 'org.springframework.boot:spring-boot-starter-test' // Include già JUnit e Mockito!
}

test {
    useJUnitPlatform()
}