# --- H2 Database configuration (in-memory) ---
#-- spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:mem:hackhubdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Enable H2 web console ---
# (Allows you to view the database in the browser at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- JPA / Hibernate configuration ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ddl-auto=update tells Spring to read @Entity and create/update
# the tables in the database automatically at each startup.
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL queries that Spring executes in the terminal (very useful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT Security ---
security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970